  ## 2.2
### (a)
supp = seq(-12, 12, 0.01)
N = 10000
U = runif(N)
f = dlogis
Finv = function(x) { -log((1-x)/x) }
X = Finv(U)
Y = rlogis(N)

par(mfrow=c(1,2))
hist(X, freq=FALSE, breaks=seq(-12, 12, 0.5), main="Logistic from Uniform")
lines(supp, f(supp), col="red", lwd=2)
hist(Y, freq=FALSE, breaks=seq(-12, 12, 0.5), main="Logistic from R")
lines(supp, f(supp), col="red", lwd=2)


### (b)
supp = seq(-12, 12, 0.01)
N = 10000
U = runif(N)
f = dcauchy
Finv = function(x) { tan(pi * (x - 1/2)) }
X = Finv(U); X = X[-12 < X & X < 12]
Y = rcauchy(N); Y = Y[-12 < Y & Y < 12]

par(mfrow=c(1,2))
hist(X, freq=FALSE, breaks=seq(-12, 12, 0.5), main="Cauchy from Uniform")
lines(supp, f(supp), col="red", lwd=2)
hist(Y, freq=FALSE, breaks=seq(-12, 12, 0.5), main="Cauchy from R")
lines(supp, f(supp), col="red", lwd=2)

## 2.3
### (b)
N = 10000
test1 = function(N) {
  U = matrix(runif(12 * N), nrow=12) - 0.5
  Z = apply(U, 2, sum)
}
test2 = function(N) {
  U1 = runif(N)
  U2 = runif(N)
  X1 = sqrt(-2 * log(U1)) * cos(2 * pi * U2)
}
par(mfrow=c(1, 2))
hist(test1(N), freq=FALSE, breaks=seq(-6, 6, 0.2), main="CLT-normal generator")
hist(test2(N), freq=FALSE, breaks=seq(-6, 6, 0.2), main="Box-Muller algorithm")

system.time(test1(N)); system.time(test2(N))

### (c)
test3 = function(N) {
  rnorm(N)
}
hist(test3(N), freq=FALSE)
system.time(test3(N))


## 2.4
### (c)
N = 10000
Sigma = cov(matrix(rnorm(30), nrow=10))

test1 = function(N) {
  A = t(chol(Sigma))
  X = matrix(runif(3 * N), nrow=N)
  X = X %*% A
}
test2 = function(N) {
  library(mnormt)
  rmnorm(N, varcov=Sigma)
}

system.time(test1(N)); system.time(test2(N))


## 2.8
### (c)
library(nimble)
N = 10000

f_inv = function(x, a) {
  f = function(x) {
    if ((0 <= x) && (x < 1/2)) {
      return(log(2*x)/a)
    }
    if ((1/2 <= x) && (x <= 1)) {
      return(-log(2*(1-x))/a)
    }
  }
  return(sapply(x, f))
}

test1 = function(N, a) {
  Y = f_inv(runif(N), a)
  M = sqrt(2*exp(1) / pi)
  U = runif(N)
  X = Y[U*ddexp(Y) < dnorm(Y)/M]
  return(X)
}

test2 = function(N) {
  U1 = runif(N)
  U2 = runif(N)
  X = sqrt(-2*log(U1)) * cos(2*pi*U2)
  return(X)
}

Xrange = seq(-4, 4, 0.001)
X1 = test1(N, 1)
X2 = test2(N)

par(mfrow=c(1, 2))
hist(X1, freq=FALSE, main="Generated by Double Exponential")
lines(Xrange, dnorm(Xrange), col="sienna", lwd=2)
hist(X2, freq=FALSE, main="Generated by Box-Muller")
lines(Xrange, dnorm(Xrange), col="sienna", lwd=2)

system.time(test1(N, 1))
system.time(test2(N))


## 2.11
### (a)
N = 10000
n = 25
p = 0.2
test1 = function(N, n, p) {
  prob = pbinom(0:n, n, p)
  X = rep(0, N)
  for (i in 1:N) {
    u = runif(1)
    X[i] = sum(prob < u)
  }
  return(X)
}
test2 = function(N, n, p) {
  return(rbinom(N, n, p))
}

system.time(test1(N, n, p))
system.time(test2(N, n, p))

X1 = test1(N, n, p)
X2 = test2(N, n, p)

par(mfrow=c(1, 2))
hist(X1, freq=FALSE, main="Generaed by inverse transform")
lines(0:n, dbinom(0:n, n, p), col="sienna", lwd=2)
hist(X2, freq=FALSE, main="Generated by rbinom")
lines(0:n, dbinom(0:n, n, p), col="sienna", lwd=2)

### (b)
N = 10000
a = 0.2
test1 = function(N, a) {
  X = rep(0, N)
  for (i in 1:N) {
    u = 2
    while(u > a) u = runif(1)
    X[i] = u
  }
  return(X)
}
test2 = function(N, a) {
  U = runif(N)
  U = a * U
  return(U)
}
test3 = function(N, a) {
  return(runif(N, max=a))
}

system.time(test1(N, a))
system.time(test2(N, a))
system.time(test3(N, a))

X1 = test1(N, a)
X2 = test2(N, a)
X3 = test3(N, a)
Xrange = seq(0, a, 0.01)

par(mfrow=c(1, 3))
hist(X1, freq=FALSE, main="Generated by the exercise code")
lines(Xrange, dunif(Xrange)/a, col="sienna", lwd=2)
hist(X2, freq=FALSE, main="Generated by aU")
lines(Xrange, dunif(Xrange)/a, col="sienna", lwd=2)
hist(X3, freq=FALSE, main="Generated by U(0, a)")
lines(Xrange, dunif(Xrange)/a, col="sienna", lwd=2)


## 2.12
### (a)
a = 3
b = 5
N = 10^4

test1 = function(N, a, b) {
  U = matrix(runif(a * N), nrow=a)
  X = b * apply(-log(U), 2, sum)
}
test2 = function(N, a, b) {
  X = rgamma(N, a, scale=b)
}
system.time(test1(N, a, b)); system.time(test2(N, a, b))

test1 = function(N, a, b) {
  U = matrix(runif((a+b) * N), nrow=a+b)
  X = -log(U)
  X = apply(X[1:a,], 2, sum) / apply(X, 2, sum)
}
test2 = function(N, a, b) {
  rbeta(N, a, b)
}
system.time(test1(N, a, b)); system.time(test2(N, a, b))


## 2.14
### (b)
N = 1000
r = 10

par(mfrow=c(1,3))
for (p in c(0.01, 0.1, 0.5)) {
  tmean = r*(1-p)/p
  tstd = sqrt(r*(1-p)/p^2)
  mrange = round(seq(max(0, tmean - 3*tstd), tmean + 3*tstd, 1))
  prob = pnbinom(mrange, r, p)
  X = rep(0, N)
  
  for (i in 1:N) {
    u = runif(1)
    X[i] = mrange[1] + sum(prob < u)
  }
  
  hist(X, freq=FALSE, main=paste("Negative Binomial with p=", p, sep=""))
  lines(dnbinom(seq(1, max(X)), r, p), col="sienna", lwd=2)
}

### (c)
N = 1000

par(mfrow=c(1, 3))
for (p in c(0.001, 0.01, 0.5)) {
  tmean = -(1-p)/(p*log(p))
  tvar = -(1-p)/(p^2*log(p)) - tmean^2
  tstd = sqrt(tvar)
  mrange = round(seq(max(1, tmean - 3*tstd), tmean + 3*tstd, 1))
  density = function(x, p) {
    -(1-p)^x/(x*log(p))
  }
  prob = cumsum(density(mrange, p))
  X = rep(1, N)
  
  for (i in 1:N) {
    u = runif(1)
    X[i] = mrange[1] + sum(prob < u)
  }
  
  M = max(X)
  
  hist(X, freq=FALSE, main=paste("Logarithmic Series with p=", p, sep=""))
  lines(density(seq(1, M), p), col="sienna", lwd=2)
}


## 2.15
N = 1000

test1 = function(N, lambda) {
  X = rep(0, N)
  for (i in 1:N) {
    K = 0
    tTime = 0
    while (TRUE) {
      tTime = tTime + rexp(1, lambda)
      if (tTime > 1)
        break
      K = K + 1
    }
    
    X[i] = K
  }
  return(X)
}

test2 = function(N, lambda) {
  X = rep(0, N)
  for (i in 1:N) {
    X[i] = rpois(1, lambda)
  }
  return(X)
}

test3 = function(N, lambda) {
  X = rep(0, N)
  spread = 3 * sqrt(lambda)
  t = round(seq(max(0, lambda - spread), lambda + spread, 1))
  prob = ppois(t, lambda)
  for (i in 1:N) {
    u = runif(1)
    X[i] = t[1] + sum(prob < u)
  }
  return(X)
}

lambda = 5

system.time(test1(N, lambda))
system.time(test2(N, lambda))
system.time(test3(N, lambda))

par(mfrow=c(1, 3))
X1 = test1(N, lambda)
X2 = test2(N, lambda)
X3 = test3(N, lambda)
Xrange = seq(min(X1, X2, X3), max(X1, X2, X3))

hist(X1, freq=FALSE, main="Generated by Poisson Process")
lines(Xrange, dpois(Xrange, lambda), col="sienna", lwd=2)
hist(X2, freq=FALSE, main="Generated by rpois")
lines(Xrange, dpois(Xrange, lambda), col="sienna", lwd=2)
hist(X3, freq=FALSE, main="Generated by Example 2.5")
lines(Xrange, dpois(Xrange, lambda), col="sienna", lwd=2)


## 2.16
N = 100000

test1 = function(N, a, b) {
  numor = runif(N)^(1/a)
  denom = numor + runif(N)^(1/b)
  numor = numor[denom <= 1]
  denom = denom[denom <= 1]
  
  X = numor / denom
  return(X)
}

test2 = function(N, a, b) {
  return(rbeta(N, a, b))
}

test3 = function(N, a, b) {
  U1 = rexp(a*N, 1)
  U1 = matrix(data=U1, nrow=a)
  U2 = rexp(b*N, 1)
  U2 = matrix(data=U2, nrow=b)
  
  numor = apply(U1, 2, sum)
  denom = numor + apply(U2, 2, sum)
  X = numor / denom
  
  return(X)
}

a = 3
b = 8

system.time(test1(N, a, b))
system.time(test2(N, a, b))
system.time(test3(N, a, b))

Xrange = seq(0, 1, 0.001)
X1 = test1(N, a, b)
X2 = test2(N, a, b)
X3 = test3(N, a, b)

par(mfrow=c(1, 3))
hist(X1, freq=FALSE, breaks=seq(0, 1, 0.05), main="Generated by uniform distribution")
lines(Xrange, dbeta(Xrange, a, b), col="sienna", lwd=2)
hist(X2, freq=FALSE, breaks=seq(0, 1, 0.05), main="Generated by rbeta")
lines(Xrange, dbeta(Xrange, a, b), col="sienna", lwd=2)
hist(X3, freq=FALSE, breaks=seq(0, 1, 0.05), "Generated by exponential distribution")
lines(Xrange, dbeta(Xrange, a, b), col="sienna", lwd=2)


## 2.18

N = 10000
supp = seq(-3, 3, 0.001)

h = function(x) { exp(-x^2/2)*(sin(6*x)^2 + 3*cos(x)^2*sin(4*x)^2 + 1) }
g = dnorm
M = 5 * sqrt(2 * pi)
X = rnorm(N)
U = runif(N)
Y = M * U * g(X)

AcceptX = X[Y <= h(X)]
RejectX = X[Y > h(X)]
rate = length(AcceptX) / N
c = rate * M
AcceptY = Y[Y <= h(X)] / c
RejectY = Y[Y > h(X)] / c
f = function(x) { h(x) / c }

par(mfrow=c(1, 1))
plot(RejectX, RejectY, xlab="", ylab="", pch=20, cex=0.5, col="gray")
points(AcceptX, AcceptY, pch=20, cex=0.5)
lines(supp, g(supp) / rate, col="orange", lwd=2)
lines(supp, f(supp), col="red", lwd=2)
legend("topright", legend=c("g(x)", "f(x)"), col=c("orange", "red"), lty=c(1, 1))


## 2.19

N = 10000
supp = seq(-10, 10, 0.001)

f = dnorm
g = function(x) { exp(-abs(x))/2 }
M = sqrt(2 * exp(1) / pi)
X = rexp(N) * (2*rbinom(N, 1, 0.5) - 1)
U = runif(N)
Y = M * U * g(X)

AcceptX = X[Y <= f(X)]
RejectX = X[Y > f(X)]
rate = length(AcceptX) / N
c = rate * M
AcceptY = Y[Y <= f(X)]
RejectY = Y[Y > f(X)]

par(mfrow=c(1, 1))
plot(RejectX, RejectY, xlab="", ylab="", pch=20, cex=0.5, col="gray")
points(AcceptX, AcceptY, pch=20, cex=0.5)
lines(supp, g(supp) / rate, col="orange", lwd=2)
lines(supp, f(supp), col="red", lwd=2)
legend("topright", legend=c("g(x)", "f(x)"), col=c("orange", "red"), lty=c(1, 1))


## 2.20
### (a)

N = 500
supp = seq(-5, 5, 0.001)

f = dnorm
g = dcauchy
M = 2 / sqrt(exp(1))
X = rcauchy(N)
U = runif(N)
Y = M * U * g(X)

AcceptX = X[Y <= f(X)]
RejectX = X[Y > f(X)]
rate = length(AcceptX) / N
c = rate * M
AcceptY = Y[Y <= f(X)]
RejectY = Y[Y > f(X)]

plot(RejectX, RejectY, xlab="", ylab="", pch=20, cex=0.5, col="gray")
points(AcceptX, AcceptY, pch=20, cex=0.5)
lines(supp, g(supp) / rate, col="orange", lwd=2)
lines(supp, f(supp), col="red", lwd=2)
legend("topright", legend=c("g(x)", "f(x)"), col=c("orange", "red"), lty=c(1, 1))

### (b)

N = 2500
supp = seq(-10, 10, 0.001)

f = dnorm
g = function(x) { exp(-abs(x))/2 }
M = sqrt(2 * exp(1) / pi)
X = rexp(N) * (2*rbinom(N, 1, 0.5) - 1)
U = runif(N)
Y = M * U * g(X)

AcceptX = X[Y <= f(X)]
RejectX = X[Y > f(X)]
rate = length(AcceptX) / N
c = rate * M
AcceptY = Y[Y <= f(X)]
RejectY = Y[Y > f(X)]

par(mfrow=c(1, 1))
plot(RejectX, RejectY, xlab="", ylab="", pch=20, cex=0.5, col="gray")
points(AcceptX, AcceptY, pch=20, cex=0.5)
lines(supp, g(supp) / rate, col="orange", lwd=2)
lines(supp, f(supp), col="red", lwd=2)
legend("topright", legend=c("g(x)", "f(x)"), col=c("orange", "red"), lty=c(1, 1))

## 2.22
### (a)
N = 10^4
mu = 0
sigma = 1

test1 = function(N, mu, sigma, a) {
  X = rep(0, N)
  for (i in 1:N) {
    z = a - 1
    while (z < a) z = rnorm(1, mu, sigma)
    X[i] = z
  }
  return(X)
}

system.time(test1(N, mu, sigma, 1))
system.time(test1(N, mu, sigma, 2))
system.time(test1(N, mu, sigma, 3))

X1 = test1(N, mu, sigma, 1)
X2 = test1(N, mu, sigma, 2)
X3 = test1(N, mu, sigma, 3)
xmax = max(X1, X2, X3)

par(mfrow=c(1, 3))
hist(X1, freq=FALSE, main="Truncated at a=1")
hist(X2, freq=FALSE, main="Truncated at a=2")
hist(X3, freq=FALSE, main="Truncated at a=3")


### (d)
N = 10^6
a = 3
M = exp(-a^2/2) / (a*sqrt(2*pi)*pnorm(-a))
dexpa = function(x, a) {
  return(dexp(x-a, a))
}
rexpa = function(n, a) {
  X = rexp(n, a)
  X = X + a
  return(X)
}
Y = rexpa(N, a)
U = runif(N)
X = Y[U*M*dexpa(Y, a) < dnorm(Y)]
hist(X, freq=FALSE, breaks=seq(3, 5, 0.1))
lines(seq(3, 5, 0.01), dnorm(seq(3, 5, 0.01))/pnorm(-3), col="sienna", lwd=2)

